/**
 * Study Momentum direction: this module keeps the approved editorial experience intact,
 * but loads only after the welcome has completed so mobile startup remains typography-led.
 * Brand asset reminder: use the supplied dark logo in the light desktop navigation and
 * the supplied light logo in the dark mobile menu, preserving their existing treatments.
 */
import { lazy, Suspense, useState, type CSSProperties, type MouseEvent as ReactMouseEvent, type ReactNode } from "react";
import { ArrowRight, Check } from "lucide-react";
import PostIntroSections from "./PostIntroSections";

const StaggeredMenu = lazy(() => import("@/components/StaggeredMenu"));
const WHATSAPP_URL = "https://wa.me/923144090277";
const INSTAGRAM_URL = "https://www.instagram.com/the.learning.lenz/";
const navItems = [["Tutor", "#tutor"], ["Subjects", "#subjects"], ["Lessons", "#lessons"], ["Method", "#method"], ["Programs", "#programs"], ["FAQs", "#faqs"]];
const mobileNavItems = [{ label: "Tutor", ariaLabel: "Meet Fatima Sattar", link: "#tutor" }, { label: "Subjects", ariaLabel: "View tutoring subjects", link: "#subjects" }, { label: "Lessons", ariaLabel: "View sample lessons", link: "#lessons" }, { label: "Method", ariaLabel: "View the learning method", link: "#method" }, { label: "Stories", ariaLabel: "Read student success stories", link: "#stories" }, { label: "Programs", ariaLabel: "View tutoring programs", link: "#programs" }, { label: "FAQs", ariaLabel: "View frequently asked questions", link: "#faqs" }];
const mobileSocialItems = [{ label: "WhatsApp", link: WHATSAPP_URL }, { label: "Instagram", link: INSTAGRAM_URL }];
let gsapLoader: Promise<typeof import("gsap").default> | null = null;
const getGSAP = () => { if (!gsapLoader) gsapLoader = import("gsap").then(({ default: gsap }) => gsap); return gsapLoader; };

function SpecularButton({ href, children, className = "", target, rel, size = "lg", radius = 18, tint = "#ffffff", tintOpacity = 0, blur = 0, textColor = "#f5f5f5", lineColor = "#ffffff", baseColor = "#525252", intensity = 1, shineSize = 10, shineFade = 40, thickness = 1, speed = 0.35, followMouse = true, proximity = 250 }: { href: string; children: ReactNode; className?: string; target?: string; rel?: string; size?: "sm" | "lg"; radius?: number; tint?: string; tintOpacity?: number; blur?: number; textColor?: string; lineColor?: string; baseColor?: string; intensity?: number; shineSize?: number; shineFade?: number; thickness?: number; speed?: number; followMouse?: boolean; proximity?: number }) {
  const [node, setNode] = useState<HTMLAnchorElement | null>(null);
  const style = { "--spec-radius": `${radius}px`, "--spec-tint": tint, "--spec-tint-opacity": tintOpacity, "--spec-blur": `${blur}px`, "--spec-text": textColor, "--spec-line": lineColor, "--spec-base": baseColor, "--spec-intensity": intensity, "--spec-shine-size": `${shineSize}px`, "--spec-shine-fade": `${shineFade}%`, "--spec-thickness": `${thickness}px`, "--spec-speed": `${speed}s`, "--spec-proximity": `${proximity}px` } as CSSProperties;
  const move = (event: React.PointerEvent<HTMLAnchorElement>) => { if (!followMouse) return; const rect = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty("--spec-x", `${((event.clientX - rect.left) / rect.width) * 100}%`); event.currentTarget.style.setProperty("--spec-y", `${((event.clientY - rect.top) / rect.height) * 100}%`); };
  const enter = () => { if (node) getGSAP().then((gsap) => gsap.to(node, { boxShadow: "0 0 0 1px rgba(217,239,255,.7), 0 12px 30px rgba(59,130,246,.18)", duration: .24, ease: "power2.out", overwrite: true })); };
  const leave = () => { if (node) getGSAP().then((gsap) => gsap.to(node, { boxShadow: "0 8px 20px rgba(23,50,77,.12)", duration: .24, ease: "power2.out", overwrite: true })); };
  return <a ref={setNode} className={`specular-button specular-${size} ${className}`} style={style} href={href} target={target} rel={rel} onPointerMove={move} onPointerEnter={enter} onPointerLeave={leave}><span className="specular-lens" /><span className="specular-content">{children}</span></a>;
}

function GooeyNav() {
  const [activeIndex, setActiveIndex] = useState(0);
  return <nav className="gooey-nav" aria-label="Primary navigation"><svg className="gooey-filter" aria-hidden="true"><defs><filter id="learning-lens-goo"><feGaussianBlur in="SourceGraphic" stdDeviation="3" result="blur" /><feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 18 -7" result="goo" /><feBlend in="SourceGraphic" in2="goo" /></filter></defs></svg>{navItems.map(([label, href], index) => <a key={label} href={href} onMouseEnter={() => setActiveIndex(index)} onFocus={() => setActiveIndex(index)} onClick={() => setActiveIndex(index)} className={activeIndex === index ? "is-active" : ""}>{activeIndex === index && <span className="gooey-active-wrap"><i className="gooey-active-pill" />{[0, 1, 2, 3].map((particle) => <b key={particle} className={`goo-particle goo-particle-${particle}`} />)}</span>}<span>{label}</span></a>)}</nav>;
}

export default function ReleasedExperience({ reduceMotion }: { reduceMotion: boolean }) {
  const mobileNavigate = (event: ReactMouseEvent<HTMLAnchorElement>, href: string) => { event.preventDefault(); window.history.pushState(null, "", href); window.setTimeout(() => document.querySelector(href)?.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" }), 270); };
  return <>
    <header className="momentum-header"><div className="page-wrap nav-wrap"><a className="momentum-brand" href="#top" aria-label="The Learning Lens home"><img className="brand-logo" src="/assets/learning-lens/brand/logo-dark.png" alt="The Learning Lens logo" loading="eager" fetchPriority="high" decoding="async" /></a><GooeyNav /><SpecularButton className="nav-specular" href={WHATSAPP_URL} target="_blank" rel="noreferrer" tint="#3b82f6" tintOpacity={0} textColor="#f5f5f5" lineColor="#d9efff" baseColor="#17324d">Book a free trial <ArrowRight size={16} /></SpecularButton><Suspense fallback={null}><StaggeredMenu items={mobileNavItems} socialItems={mobileSocialItems} logoUrl="/assets/learning-lens/brand/light-logo.png" onNavigate={mobileNavigate} /></Suspense></div></header>
    <main className="released-experience"><section className="hero-v2 hero-centered-v4" id="hero" aria-labelledby="hero-title"><div className="hero-atmosphere" aria-hidden="true"><span className="hero-paper-grid" /></div><div className="page-wrap hero-copy-v2 hero-copy-centered-v4"><p className="hero-kicker">Accounting &amp; Business tutoring</p><h2 id="hero-title">Make the paper <em>make sense.</em></h2><p className="hero-lead">Clear, targeted support for the topic, paper, or exam that is holding you back.</p><div className="hero-actions-v2"><SpecularButton href={WHATSAPP_URL} target="_blank" rel="noreferrer" tint="#3b82f6" tintOpacity={0} textColor="#f5f5f5" lineColor="#d9efff" baseColor="#17324d">Book a free trial <ArrowRight size={18} /></SpecularButton><a className="button-quiet-v2" href="#subjects">View subjects</a></div></div></section><section className="tutor-v2" id="tutor" data-scroll-section aria-labelledby="tutor-title"><div className="tutor-atmosphere" aria-hidden="true" /><div className="page-wrap tutor-grid-v2"><div className="tutor-label"><span>01</span><p>Meet your tutor</p></div><div className="tutor-copy-v2"><p className="eyebrow-v2">An experienced guide, not a corporate bio</p><h2 id="tutor-title">Hi, I’m <em>Fatima Sattar.</em></h2><p className="body-large-v2">I didn't set out to be a teacher. I was the student who struggled, doubted myself, and wondered if I was just not good enough, until Accounting finally clicked and showed me what the right teacher can do. After ACCA, I tried the corporate route, but the part I actually loved was always helping someone else understand something. So I started The Learning Lens. Six years and hundreds of students later across O Level, IGCSE, A Level, and ACCA, I still believe every “stuck” subject just needs the right explanation.</p><div className="tutor-credentials-v4"><span><small>Experience</small><b>6+ years teaching</b></span><span><small>Perspective</small><b>ACCA F2 national place winner</b></span></div><a className="inline-link-v2" href={WHATSAPP_URL} target="_blank" rel="noreferrer">Start working with me <ArrowRight size={17} /></a></div><div className="tutor-points"><span>What to expect</span><p><Check size={17} />Clear explanations, made for the way you learn.</p><p><Check size={17} />Active exam technique, not passive worksheets.</p><p><Check size={17} />Calm, consistent support as you improve.</p><div className="tutor-pulse" /></div></div></section><PostIntroSections reduceMotion={reduceMotion} onReady={() => undefined} /></main>
  </>;
}
